[스택,큐,덱] 3월 17일
Altu-Bitu-2/AltuBitu_Algorithm pull request #4
Opened 2022-03-16 19:38 UTC by zziyuni

#### 내용 & 질문
> 1213번 코드에 오류가 있습니다! 자세한건 주석으로 써놨습니다:)
다른 방법으로 풀어볼까 했지만 해당 코드로 썼을 때 왜 안되는지 궁금해서 고치지 않고 냅니다!!
2108번 백준에 있는 예제코드도 제대로 돌아가고 다시 확인해봐도 빠진 조건이 없는거 같은데 제출했을 때 틀렸다고 나옵니다ㅠㅠ
어디가 잘못된건지 알고싶습니다!
남은 문제는 추가적으로 더 풀어서 제출하도록 하겠습니다.

#### <기존 제출>
> 1213, 2108

#### <추가 제출>
>X

2022-03-17 07:17 UTC, bsa0322 reviewed
안녕하세요 😊 아래에 코멘트 더 있으니 참고해주세요!!

2022-03-17 07:17 UTC, bsa0322 commented on 0311-stack,queue,deque/1213.cpp
> +        else if(strcmp(d.front() == iter)){ //set의 다음 문자가 덱의 front에 넣은 문자와 같다면 덱의 rear에 삽입, 문자 비교함수 쓰고 싶은데 에러남
strcmp 함수의 구조를 보면 다음과 같이 생겼어요!
```cpp
int strcmp(const char* str1, const char* str2)
```
따라서 우선 매개로 넘겨줄 때 ==의 형태가 아니라, 문자열 2개를 콤마로 구분해서 넘겨주어야 합니다. 더불어 인자의 형태가 char* 이기 때문에 char 문자열만 넘겨줄 수 있어요! 즉, 지금의 d.front()는 그냥 문자 하나인 char 형이고, iter는 string 형이기 때문에 strcmp를 사용할 수 없습니다 😂

2022-03-17 07:17 UTC, bsa0322 commented on 0311-stack,queue,deque/2108.cpp
> +    calcRange(v);
p2. 함수는 리턴형이 있어야 구조와 역할이 더 명확하기에 가급적 void형 함수는 피해주는 게 좋아요! 특히 문제의 정답에 대한 출력은 main() 에서 해주시는 편이 좋습니다. 함수는 정확히 특정 역할을 수행하는 게 좋은데, 그 함수를 여러 번 사용할 때마다 출력이 나오면 곤란할 수 있겠죠! 따라서 디버깅 용 출력이 아닌 이상 함수 안에서의 출력은 피해주는 게 좋아요. 
해당 문제는, 각 값들을 리턴해주는 함수로 만들어서 main에서 출력해 주도록 짤 수 있겠네요!

2022-03-17 07:45 UTC, bsa0322 requested changes
p1. 코멘트 남겼습니다! 힌트 더 필요하시면 언제든 불러주세요! 리뷰어로 호출해주시면 됩니다~! 과제하느라 수고하셨습니다 😊🥰

2022-03-17 07:45 UTC, bsa0322 commented on 0311-stack,queue,deque/2108.cpp
> +    cout << * ms.begin()<<"\n";
p1. 현재 map에 삽입하고 다시 삭제해서 중앙값을 구하는 방법은 비효율적인 풀이예요! 지금은 정렬만 필요한 경우이기에 map보다 sort를 써주시는 것이 좋아요! map은 삽입, 삭제 시 시간복잡도가 O(logN)으로 n개의 데이터를 삽입하면 O(nlogn)의 시간복잡도가 걸리고 여기서 지금 삭제까지 이루어지고 있으니 시간이 더 걸릴거예요. 
반면에 sort는  O(nlogn)의 시간복잡도가 걸리고, 기존 vector의 값을 정렬하는 것이기 때문에 랜덤한 인덱스에 접근도 가능할 거예요. 
더불어 sort는 기존의 데이터를 정렬하는 거라서 추가적인 메모리가 필요하지 않은데, 지금은 map을 써서 불필요한 메모리를 더 사용하고 있는 셈이예요! 따라서 sort를 사용해주시면 더욱 효율적으로 코드를 짤 수 있습니다 😊
또한 문제에서 **n은 항상 홀수**라고 했어요! 그럼 sort를 활용해서 중앙값에 바로 접근해 줄 수 있겠죠 😉

2022-03-17 07:45 UTC, bsa0322 commented on 0311-stack,queue,deque/2108.cpp
> +    int maxKey;
문제에서 항상 양수라는 보장이 없어요! max의 초기화 값을 무엇으로 해야 할까요?

2022-03-17 07:45 UTC, bsa0322 commented on 0311-stack,queue,deque/2108.cpp
> +    }
최빈값이 여러 개일 경우, 두 번째로 작은 값을 구해주는 부분이 잘 이루어지지 않고 있어요. tmp에 맵의 second 값을 넣어주는 건 최빈값의 횟수를 넣어주는 것이죠. 이때 최빈값이 유일하게 있다고 tmp.size()가 1이라는 보장은 없죠! 
예를 들어, 1 1 2 3 3 3 일 경우, 3만 유일한 최빈값인데 tmp에 들어가는 값은 1 (2의 개수) 2 (1의 개수) 3 (3의 개수) 겠죠! 따라서 **값의 횟수가 최대 횟수와 같은 지를 비교**하면서 같은 값들을 모은 후에 그 중에서 두 번째로 작은 값을 구해야해요. 이때도 sort를 사용해주는 편이 좋습니다! 😊

2022-03-17 07:45 UTC, bsa0322 commented on 0311-stack,queue,deque/2108.cpp
> +    cout<<range<<"\n";
p1. 범위 또한 set보다 더 효율적인 풀이가 있어요! **set과 map은 정렬이 필요할 때 보단, 검색이 필요할 때** 사용해주시는 편이 더 효율적입니다! 랜덤한 인덱스에 접근이 불가하다는 점이 불편하기도 하구요. sort를 활용해서 범위를 구해볼까요!

2022-03-19 14:38 UTC, jaeseo222 commented
최종적으로 필수 2문제, 선택 4문제 확인했습니다!
머지해주셔도 됩니다! 감사합니다 🥰🥰

2022-03-20 10:34 UTC, merged